services:
    debian_builder:
        build:
            context: .
            dockerfile: ./docker/deb/Dockerfile
        command: tail -f /dev/null
    rpm_builder:
        build:
            context: .
            dockerfile: ./docker/rpm/Dockerfile
        command: tail -f /dev/null
    win_builder:
        build:
            context: .
            dockerfile: ./docker/win/Dockerfile
        command: tail -f /dev/null
