name: respond
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - benchmark=1.8.4=hac33072_1
  - eigen=3.4.0=h00ab1b0_0
  - fmt=10.2.1=h00ab1b0_0
  - gtest=1.15.0=h434a139_0
  - spdlog>=1.13.0
  - pip:
      - pybind11-global==2.13.1
      - respond==1.0.0
