name: Windows Unit Tests

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        name: Build Windows Tests
        uses: ./.github/workflows/build.yml
        with:
            build-type: Debug
            os: windows-latest
            platform: 2022
            generator: MinGW Makefiles
            asset-name: respond_tests
            asset-path: "build\\tests\\Debug\\respond_tests.exe"
            cmake-vars: -D RESPOND_BUILD_PIC=ON -D RESPOND_BUILD_EXECUTABLE=OFF -D RESPOND_BUILD_TESTS=ON -D RESPOND_CALCULATE_COVERAGE=OFF -D RESPOND_BUILD_BENCH=OFF -D RESPOND_BUILD_WARNINGS=ON -D RESPOND_BUILD_SHARED_LIBS=OFF
    test:
        needs: build
        name: Test Windows Libraries
        runs-on: windows-latest
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: windows-latest-Debug-respond_tests
            - name: Run Windows Tests
              run: |
                .\respond_tests.exe
